name: pull request
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: '~./npm'
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run ci
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: '~./npm'
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies

        run: npm install
      - name: build code
        run: echo 'simulating code build'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo 'simulationg code deploy'
